#let tr = text.with(rgb("#ff1d1d"))
#let tg = text.with(rgb("#1dff4a"))
#let tb = text.with(rgb("#1d66ff"))
#let ty = text.with(rgb("#fffa1d"))
#let to = text.with(rgb("#ff9f1d"))
#let tp = text.with(rgb("#ff1dff"))
#let tc = text.with(rgb("#1dfff6"))
#let tgray = text.with(rgb("#888888"))
